
version: "3.8"
networks:
  antifraud_network:

x-service-template: &template
  restart: on-failure
  extra_hosts:
    host.docker.internal: host-gateway
  networks:
    - antifraud_network

services:
  workflow:
    <<: *template
    build:
      context: .
      dockerfile: local/Dockerfile
    hostname: &name workflow
    container_name: *name
    ports:
      - "18080:18080"
    profiles:
      - rest
    environment:
      TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS:-temporal:7233}
      WORKFLOW_WEB_PORT: 18080

  workflow-grpc:
    <<: *template
    build:
      context: .
      dockerfile: local/Dockerfile
    hostname: &name workflow-grpc
    container_name: *name
    command: anti-fraud-grpc.jar
    profiles:
      - grpc
    environment:
      TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS:-temporal:7233}

  worker:
    <<: *template
    build:
      context: .
      dockerfile: local/Dockerfile
    hostname: worker
    command: anti-fraud-worker.jar
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
    profiles:
      - worker
    environment:
      TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS:-temporal:7233}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres:
    <<: *template
    image: postgres
    hostname: &name postgres
    container_name: *name
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    profiles:
      - base
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  temporal:
    <<: *template
    image: temporalio/auto-setup
    hostname: &name temporal
    container_name: *name
    depends_on:
      - postgres
    ports:
      - "7233:7233"
    profiles:
      - base
    environment:
      DB: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PWD: postgres
      POSTGRES_SEEDS: postgres

  temporal-admin-tools:
    <<: *template
    image: temporalio/admin-tools
    hostname: &name temporal-admin-tools
    container_name: *name
    stdin_open: true
    tty: true
    depends_on:
      - temporal
    profiles:
      - base
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CLI_ADDRESS: temporal:7233

  temporal-ui:
    <<: *template
    image: temporalio/ui
    hostname: &name temporal-ui
    container_name: *name
    depends_on:
      - temporal
    ports:
      - "8080:8080"
    profiles:
      - base
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000

  k6:
    <<: *template
    image: grafana/k6
    hostname: &name k6
    container_name: *name
    entrypoint: tail -f /dev/null
    volumes:
      - ./performance-tests/index.js:/index.js
      - ./performance-tests/grpc.js:/grpc.js
      - ./anti-fraud-temporal-contract/src/main/proto/anti_fraud.proto:/definitions/anti_fraud.proto
    profiles:
      - perf
    environment:
      TEMPORAL_WORKFLOW_WEB_ADDRESS: ${TEMPORAL_WORKFLOW_WEB_ADDRESS:-workflow:18080}
      TEMPORAL_WORKFLOW_GRPC_ADDRESS: ${TEMPORAL_WORKFLOW_GRPC_ADDRESS:-workflow-grpc:7777}
